import {acceptTitle} from './accept_title.mjs';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),up=path.resolve(root,'../../../TSRun'),api=await import(pathToFileURL(path.join(up,'machine.js')));
const sym=Object.fromEntries([...fs.readFileSync(path.join(root,'build/mining-symbols.txt'),'utf8').matchAll(/^(\w+): EQU 0x([0-9A-F]+)/gm)].map(x=>[x[1],parseInt(x[2],16)]));
const keys=new Uint8Array(8).fill(31),m=api.createMachine(keys,new Uint8Array(2).fill(255));m.homeRom.set(fs.readFileSync(path.join(up,'roms/ts2068-0.rom')));m.exRom.set(fs.readFileSync(path.join(up,'roms/ts2068-1.rom')));api.insertDock(m,fs.readFileSync(path.join(root,'build/sinistar-mining.dck')));api.resetMachine(m);acceptTitle(m,sym);
const names=['game_step','wb_population','wb_worker','wb_move_player','render','population_clear','population_draw','stage','compile','radar_entry','stars_clear','stars_draw','draw_assembly','draw_cached_face','fast_select','wb_pop_prepare','wb_clip_sprite'],stats=Object.fromEntries(names.map(n=>[n,{calls:0,cycles:0}]));const pending=[];let pics=0,started=0;const visibleHistogram={};let clippedPlanetoids=0,visibilitySamples=0;
const read=m.bus.read;m.bus.read=a=>{if(a===m.cpu.pc){for(let i=pending.length-1;i>=0;i--){const p=pending[i];if(a===p.ret&&m.cpu.sp===p.sp+2){stats[p.n].cycles+=m.tstates-p.time;pending.splice(i,1);}}for(const n of names)if(a===sym[n]){stats[n].calls++;pending.push({n,ret:m.ram[m.cpu.sp]|m.ram[m.cpu.sp+1]<<8,sp:m.cpu.sp,time:m.tstates});}if(a===sym.frame_done){pics++;if(!started)started=m.tstates;}}return read(a);};
const instrumentedRead=m.bus.read;m.bus.read=a=>{if(a===m.cpu.pc&&a===sym.fast_select){let visible=m.ram[sym.rects+2]?1:0;for(let p=0xbc80;p<0xbc80+153;p+=9){if(m.ram[p+2]){visible++;if(m.ram[p+2]!==5||m.ram[p+3]!==28)clippedPlanetoids++;}}visibleHistogram[visible]=(visibleHistogram[visible]||0)+1;visibilitySamples++;}return instrumentedRead(a);};
for(let i=0;i<1200;i++){if(i===250)keys[5]&=~1;if(i===700){keys.fill(31);keys[1]&=~1;}api.runFrame(m);}
const report={dck_sha256:createHash('sha256').update(fs.readFileSync(path.join(root,'build/sinistar-mining.dck'))).digest('hex'),pictures:pics,fps:(pics-1)/((m.tstates-started)/3528000),visibleHistogram,clippedPlanetoids,visibilitySamples,stats:Object.fromEntries(Object.entries(stats).map(([n,v])=>[n,{...v,average:Math.round(v.cycles/v.calls)}]))};console.log(report);fs.writeFileSync(path.join(root,'build/scrolling-profile.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(root,'build/scrolling-screen.ram'),m.ram);
