import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {acceptTitle} from './accept_title.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),up=path.resolve(root,'../../../TSRun');const api=await import(pathToFileURL(path.join(up,'machine.js')));
const sym=Object.fromEntries([...fs.readFileSync(path.join(root,'build/mining-symbols.txt'),'utf8').matchAll(/^(\w+): EQU 0x([0-9A-F]+)/gm)].map(x=>[x[1],parseInt(x[2],16)]));const cart=fs.readFileSync(path.join(root,'build/sinistar-mining.dck'));const dir=path.join(root,'build/death-sequences');fs.mkdirSync(dir,{recursive:true});
function machine(){const m=api.createMachine(new Uint8Array(8).fill(31),new Uint8Array(2).fill(255));m.homeRom.set(fs.readFileSync(path.join(up,'roms/ts2068-0.rom')));m.exRom.set(fs.readFileSync(path.join(up,'roms/ts2068-1.rom')));api.insertDock(m,cart);api.resetMachine(m);acceptTitle(m,sym);for(let i=0;i<400&&m.ram[sym.game_mode]!==1;i++)api.runFrame(m);assert.equal(m.ram[sym.game_mode],1);for(let i=0;i<20;i++)api.runFrame(m);return m;}
function word(m,a,v){m.ram[a]=v&255;m.ram[a+1]=v>>8;}
function setup(m){for(const [n,v] of Object.entries({sinistar_built:1,assembly_count:20,awake_done:1,speech_started:1,worker_alive:0,worker_delay:255,invulnerable:255}))m.ram[sym[n]]=v;for(const [n,v] of Object.entries({face_x:120*256,face_y:90*256,px:60*256,py:112*256,pvx:0,pvy:0,face_vx:0,face_vy:0}))word(m,sym[n],v);for(const a of [0x7c96,0x7c97,0x7c98,0x7c99,0x7c9a,0x7c9b])m.ram[a]=0;word(m,0x5884,0);word(m,0x5886,0);}
const results={};
for(const kind of ['player','sinistar']){const m=machine();setup(m);let captures=0,romWrites=0,startT=null,endT=null;const pictureTimes=[];const waves=new Set(),read=m.bus.read,write=m.bus.write;m.bus.write=(a,v)=>{if(a>=0x4000&&(m.portF4&(1<<(a>>13))))romWrites++;write(a,v);};m.bus.read=a=>{if(a===m.cpu.pc&&a===sym.death_start&&startT===null)startT=m.tstates;if(a===m.cpu.pc&&a===sym.death_finish)endT=m.tstates;if(a===m.cpu.pc&&a===sym.publication_done&&m.ram[0x7bfb]){assert.equal(m.ram[sym.rects+14],kind==='player'?0:3,'player visibility during sequence');waves.add(m.ram[0x7bfd]);pictureTimes.push({t:m.tstates,wave:m.ram[0x7bfd]});fs.writeFileSync(path.join(dir,`${kind}-${String(captures++).padStart(3,'0')}.bin`),Buffer.concat([Buffer.from(m.ram.slice(0x4000,0x5800)),Buffer.from(m.ram.slice(0x6000,0x7800))]));}return read(a);};
 if(kind==='player'){m.ram[sym.invulnerable]=0;word(m,sym.px,132*256);word(m,sym.py,102*256);}else m.ram[sym.bs_hits]=13;
 let started=false;for(let i=0;i<360;i++){api.runFrame(m);if(m.ram[0x7bfb])started=true;if(started&&!m.ram[0x7bfb])break;}
 console.log({kind,captures,timer:m.ram[0x7bfc],wave:m.ram[0x7bfd],pc:m.cpu.pc.toString(16),frames:m.ram[sym.frames],state:m.ram[0x7bfb]});assert.ok(started);assert.equal(m.ram[0x7bfb],0,'sequence terminates');assert.ok(captures>=4);assert.ok(waves.size>=3);assert.equal(romWrites,0);if(kind==='player'){assert.equal(m.ram[sym.lives],2);assert.ok(m.ram[sym.invulnerable]>0);}else assert.equal(m.ram[sym.game_status],1);results[kind]={pictures:captures,waves:[...waves],romWrites,durationSeconds:(endT-startT)/3528000,firstExplosionMs:(pictureTimes.find(p=>p.wave>0).t-startT)/3528,meanPictureFps:(pictureTimes.length-1)*3528000/(pictureTimes.at(-1).t-pictureTimes[0].t)};}
const m=machine();let configured=false,lastX=100;const rd=m.bus.read;m.bus.read=a=>{if(a===m.cpu.pc&&a===sym.game_step){if(!configured){setup(m);m.ram[sym.worker_alive]=1;m.ram[sym.worker_x]=100;m.ram[sym.worker_y]=112;configured=true;}else lastX=m.ram[sym.worker_x];}return rd(a);};for(let i=0;i<40;i++)api.runFrame(m);assert.ok(lastX<100,'idle built-world worker intercepts player');results.harassment={startX:100,endX:lastX};results.dck_sha256=createHash('sha256').update(cart).digest('hex');fs.writeFileSync(path.join(root,'build/worker-death-verification.json'),JSON.stringify(results,null,2));console.log(results);
