import {acceptTitle} from './accept_title.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),up=path.resolve(root,'../../../TSRun');
const api=await import(pathToFileURL(path.join(up,'machine.js'))),dir=path.join(root,'build/local-pulse-video');fs.mkdirSync(dir,{recursive:true});
const base=path.join(root,'revisions/playable-local-bright-v9/build');
const sym=Object.fromEntries([...fs.readFileSync(path.join(base,'mining-symbols.txt'),'utf8').matchAll(/^(\w+): EQU 0x([0-9A-F]+)/gm)].map(x=>[x[1],parseInt(x[2],16)]));
const m=api.createMachine(new Uint8Array(8).fill(31),new Uint8Array(2).fill(255));m.homeRom.set(fs.readFileSync(path.join(up,'roms/ts2068-0.rom')));m.exRom.set(fs.readFileSync(path.join(up,'roms/ts2068-1.rom')));api.insertDock(m,fs.readFileSync(path.join(base,'sinistar-mining.dck')));api.resetMachine(m);acceptTitle(m,sym);
let frame=-120,next=0;const targets=[60,180,300],events=[],brightness=[];
const put=(a,v)=>{m.ram[a]=v;m.ram[a+1]=v>>8;},records=[...Array.from({length:8},(_,i)=>0x79b0+i*10),...Array.from({length:8},(_,i)=>0x7db0+i*10),0x58b4];
const read=m.bus.read;m.bus.read=a=>{if(a===m.cpu.pc&&a===sym.frame_start){put(0x5884,0);put(0x5886,0);put(sym.face_x,96*256);put(sym.face_y,90*256);m.ram[0x7c9a]=m.ram[0x7c9b]=0;put(sym.px,32*256);put(sym.py,110*256);m.ram[0x7c96]=m.ram[0x7c97]=0;for(const [n,v] of Object.entries({assembly_count:20,sinistar_built:1,awake_done:1,awake_mouth:0,bs_hits:0,invulnerable:255,worker_alive:0,rock_alive:0,bullet_alive:0,crystal_alive:0,bs_active:0,game_status:0,speech_started:1,speech_pending:0,speech_left:0}))m.ram[sym[n]]=v;for(const p of records){put(p,350);put(p+2,350);m.ram[p+7]=96;}if(next<targets.length&&frame>=targets[next]){m.ram[0x783e]=7;m.ram[0x783f]=7;events.push(frame);next++;}}return read(a);};
const out=fs.openSync(path.join(dir,'frames.idx'),'w');
for(;frame<360;frame++){api.runFrame(m);if(frame>=0){fs.writeSync(out,m.pixels);let bright=0;for(let y=114;y<166;y++)for(let x=256;x<368;x++)if(m.pixels[y*640+x]&8)bright++;brightness.push(bright);}}
fs.closeSync(out);assert.equal(events.length,3);assert.ok(brightness.some(n=>n>0));fs.writeFileSync(path.join(dir,'capture.json'),JSON.stringify({width:640,height:240,fps:3528000/58688,frames:360,events,brightness,source:'Saved v9 cartridge; native effect requests injected in a stationary fixture; actual TSRun raster pixels, not RAM snapshots'},null,2));console.log({events,brightFrames:brightness.map((n,i)=>n?i:null).filter(n=>n!==null)});
